const mongoose = require('mongoose');

const messageSchema = new mongoose.Schema({
  content: {
    type: String,
    required: true,
  },
  sender: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  channelId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Channel',
    required: true,
  },
  isPinned: {
    type: Boolean,
    default: false,
  },
  reactions: {
    type: Map,
    of: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    }],
    default: new Map()
  },
  attachments: [{
    url: String,
    type: { type: String }, // 'image', 'file', etc.
    name: String
  }],
  type: {
    type: String,
    enum: ['text', 'system'],
    default: 'text'
  },
  replyTo: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Message',
    default: null
  },
  isEdited: {
    type: Boolean,
    default: false
  },
  editedAt: {
    type: Date,
    default: null
  },
  // clientId: stable UUID generated by the client, used to deduplicate
  // offline-queued messages that may be sent more than once during sync
  clientId: {
    type: String,
    default: null,
    index: true,
    sparse: true // null values don't conflict; only non-null are uniqueness-checked
  }
}, { timestamps: true });

// Partial unique index: enforce uniqueness only for documents where clientId is set
messageSchema.index(
  { clientId: 1, sender: 1 },
  { unique: true, sparse: true, partialFilterExpression: { clientId: { $type: 'string' } } }
);


module.exports = mongoose.model('Message', messageSchema);
